SG-35935 first phase python2 removing
shotgunsoftware/tk-framework-desktopclient pull request #25
Opened 2024-07-27 08:05 UTC by eduardoChaucaGallegos

- Six ensure functions replaced with function from sgutils

2024-07-29 12:45 UTC, julien-lang requested changes
I don't think we should "patch" the third-party libraries we bundle in Vendors/.
Can we update the library instead maybe?

Or was these libraries were manually patches before for Python 3 support?

2024-07-29 13:01 UTC, carlos-villavicencio-adsk commented
> I don't think we should "patch" the third-party libraries we bundle in Vendors/. Can we update the library instead maybe?
> 
> Or was these libraries were manually patches before for Python 3 support?

Julien is right. This component has its own six [here](https://github.com/shotgunsoftware/tk-framework-desktopclient/tree/master/Vendors). Maybe we should leave it as it is for now. It's also required to separate the libraries per python version at some point.

2024-08-02 18:50 UTC, julien-lang commented on Vendors/bin/wsdump.py
I think this file is part of the websocket_client third party (only call from there) so I think we should drop changes from this file too.

2024-08-02 21:26 UTC, julien-lang approved these changes

2024-08-02 22:37 UTC, carlos-villavicencio-adsk approved these changes
LGTM

2024-09-07 00:33 UTC, merged